[project]
id = "com.veezor.demo-site"
name = "DemoSite"
version = "1.0"

[build]
builder = "heroku/buildpacks:20"

[[build.buildpacks]]
uri = "heroku/php"

[[build.buildpacks]]
uri = "heroku/procfile"