version: 0.2
phases:
  install:
    commands:
      - PYTHON=python2 amazon-linux-extras enable docker > /dev/null
      - yum -y -q install amazon-ecr-credential-helper python-pip
      - pip install awscli
  pre_build:
    commands:
      - PACK_VERSION=v0.20.0
      - (curl -sSL "https://github.com/buildpacks/pack/releases/download/$PACK_VERSION/pack-$PACK_VERSION-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - mkdir -p ~/.docker && echo '{"credsStore":"ecr-login"}' > ~/.docker/config.json
      - COMMIT="$(git rev-parse --short=8 HEAD)"
      - BRANCH="$(git name-rev --name-only HEAD)"
  build:
    commands:
      - pack build $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/veezor-veezor_demo-$BRANCH:$GITHUB_SHA_SHORT --cache-image $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/veezor-static-site-$BRANCH:cache -v --builder heroku/buildpacks:20 --pull-policy if-not-present --publish